"""add top_position to ratings

Revision ID: f6b31a4ebf50
Revises: f8ace6963039
Create Date: 2026-07-06 03:39:37.946066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b31a4ebf50'
down_revision: Union[str, Sequence[str], None] = 'f8ace6963039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('top_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'top_position')
    # ### end Alembic commands ###
